### PR TITLE
Fix remaining entry issues

### LINKED ISSUE #41: Add form instructions/placeholders to improve learnability
- [x] registration form
- [x] add user form
- [x] medication form
- [x] insurance form
- [x] entry form (#44)

related to and comes after #32

### LINKED ISSUE #94: Buttons in view more section of log table don't align properly when notes only one line
Screen Shot 2022-12-11 at 12 22 28 PM

### LINKED ISSUE #96: Disallow revoking access with only one credential left

### PR DESCRIPTION
**Pull request by wli-linda**
Closes #94
Partially address #87 
Closes #41 
Closes #96

### CODE REVIEW

File: client/components/common/BaseForm.vue [hunk 1]
```diff
@@ -22,6 +22,14 @@
         >
         {{ text }}
         </option>
+        <option
```
Comment (jrdegreeff) [inline client/components/common/BaseForm.vue]: This feels very hacky to me and not generic. what is the intended result?

File: client/components/common/BaseForm.vue [hunk 2]
```diff
@@ -95,6 +103,7 @@ export default {
     this.fields.forEach(f => {
       const validators = [
         !f.optional && (v => v ? '' : 'required field'),
+        !f.optional && this.$helpers.validators.nonEmpty,
```
Comment (jrdegreeff) [inline client/components/common/BaseForm.vue:102]: I'd rather not add this since we already added in all the other specific places

File: client/components/common/BaseForm.vue [hunk 3]
```diff
@@ -125,6 +134,9 @@ export default {
     update(id) {
       this.customUpdaters[id] && this.customUpdaters[id](this);  // escape hatch
     },
+    formatContact(contact) {
+      return contact ? `${contact.title} ${contact.first_name} ${contact.last_name}` : '';
+    },
```
Comment (jrdegreeff) [inline client/components/common/BaseForm.vue]: as above, I don't think this should be here.

**Review by jrdegreeff — CHANGES_REQUESTED** [review]

File: client/components/common/BaseForm.vue (hunk 2 above)
Comment (wli-linda) [reply client/components/common/BaseForm.vue:102]: would it be better to just have it here and remove from specific places? I can't think of a good reason for why required fields could be empty / why optional fields need to be nonEmpty

**Review by jrdegreeff — DISMISSED** [review]

File: client/components/common/BaseForm.vue (hunk 2 above)
Comment (jrdegreeff) [reply client/components/common/BaseForm.vue:102]: that would be reasonable as well. I'm going offline now, but feel free to do it that way across the board if you prefer.  My only objection is to the duplication.

**Review by jrdegreeff — APPROVED** [review]
looks good. I like the simple workaround for #96.
